package com.example.notekit.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF535A92)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDFE0FF)
val onPrimaryContainerLight = Color(0xFF3B4279)
val secondaryLight = Color(0xFF5B5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E0F9)
val onSecondaryContainerLight = Color(0xFF434559)
val tertiaryLight = Color(0xFF77536C)
val onTertiaryLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1B1B21)

val primaryDark = Color(0xFFBCC2FF)
val onPrimaryDark = Color(0xFF242B61)
val primaryContainerDark = Color(0xFF3B4279)
val onPrimaryContainerDark = Color(0xFFDFE0FF)
val secondaryDark = Color(0xFFC4C5DD)
val onSecondaryDark = Color(0xFF2D2F42)
val secondaryContainerDark = Color(0xFF434559)
val onSecondaryContainerDark = Color(0xFFE0E0F9)
val tertiaryDark = Color(0xFFE6BAD6)
val onTertiaryDark = Color(0xFF45263D)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)